const dummyData = [
    {
        "id": 1499324400,
        "date": "2017-07-06",
        "productivity_pulse": 48,
        "very_productive_percentage": 39.6,
        "productive_percentage": 5.6,
        "neutral_percentage": 8.3,
        "distracting_percentage": 0.8,
        "very_distracting_percentage": 45.6,
        "all_productive_percentage": 45.2,
        "all_distracting_percentage": 46.4,
        "uncategorized_percentage": 4.3,
        "business_percentage": 3.9,
        "communication_and_scheduling_percentage": 21,
        "social_networking_percentage": 2.7,
        "design_and_composition_percentage": 0.2,
        "entertainment_percentage": 17.9,
        "news_percentage": 7.9,
        "software_development_percentage": 34.6,
        "reference_and_learning_percentage": 0.8,
        "shopping_percentage": 0.7,
        "utilities_percentage": 5.9,
        "total_hours": 13.54,
        "very_productive_hours": 5.36,
        "productive_hours": 0.76,
        "neutral_hours": 1.13,
        "distracting_hours": 0.11,
        "very_distracting_hours": 6.18,
        "all_productive_hours": 6.12,
        "all_distracting_hours": 6.29,
        "uncategorized_hours": 0.59,
        "business_hours": 0.53,
        "communication_and_scheduling_hours": 2.85,
        "social_networking_hours": 0.36,
        "design_and_composition_hours": 0.03,
        "entertainment_hours": 2.42,
        "news_hours": 1.07,
        "software_development_hours": 4.68,
        "reference_and_learning_hours": 0.11,
        "shopping_hours": 0.09,
        "utilities_hours": 0.8,
        "total_duration_formatted": "13h 32m",
        "very_productive_duration_formatted": "5h 21m",
        "productive_duration_formatted": "45m 50s",
        "neutral_duration_formatted": "1h 7m",
        "distracting_duration_formatted": "6m 32s",
        "very_distracting_duration_formatted": "6h 10m",
        "all_productive_duration_formatted": "6h 7m",
        "all_distracting_duration_formatted": "6h 17m",
        "uncategorized_duration_formatted": "35m 6s",
        "business_duration_formatted": "32m 1s",
        "communication_and_scheduling_duration_formatted": "2h 50m",
        "social_networking_duration_formatted": "21m 41s",
        "design_and_composition_duration_formatted": "2m 1s",
        "entertainment_duration_formatted": "2h 25m",
        "news_duration_formatted": "1h 4m",
        "software_development_duration_formatted": "4h 40m",
        "reference_and_learning_duration_formatted": "6m 30s",
        "shopping_duration_formatted": "5m 27s",
        "utilities_duration_formatted": "47m 58s"
    },
    {
        "id": 1499238000,
        "date": "2017-07-05",
        "productivity_pulse": 15,
        "very_productive_percentage": 1,
        "productive_percentage": 2.8,
        "neutral_percentage": 22.7,
        "distracting_percentage": 2.2,
        "very_distracting_percentage": 71.3,
        "all_productive_percentage": 3.8,
        "all_distracting_percentage": 73.5,
        "uncategorized_percentage": 14.1,
        "business_percentage": 0,
        "communication_and_scheduling_percentage": 28.3,
        "social_networking_percentage": 8,
        "design_and_composition_percentage": 0.1,
        "entertainment_percentage": 32,
        "news_percentage": 3.9,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 0.9,
        "shopping_percentage": 0,
        "utilities_percentage": 12.7,
        "total_hours": 5.48,
        "very_productive_hours": 0.06,
        "productive_hours": 0.15,
        "neutral_hours": 1.24,
        "distracting_hours": 0.12,
        "very_distracting_hours": 3.9,
        "all_productive_hours": 0.21,
        "all_distracting_hours": 4.02,
        "uncategorized_hours": 0.77,
        "business_hours": 0,
        "communication_and_scheduling_hours": 1.55,
        "social_networking_hours": 0.44,
        "design_and_composition_hours": 0.01,
        "entertainment_hours": 1.75,
        "news_hours": 0.21,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.05,
        "shopping_hours": 0,
        "utilities_hours": 0.69,
        "total_duration_formatted": "5h 28m",
        "very_productive_duration_formatted": "3m 21s",
        "productive_duration_formatted": "9m 17s",
        "neutral_duration_formatted": "1h 14m",
        "distracting_duration_formatted": "7m 10s",
        "very_distracting_duration_formatted": "3h 54m",
        "all_productive_duration_formatted": "12m 38s",
        "all_distracting_duration_formatted": "4h 1m",
        "uncategorized_duration_formatted": "46m 28s",
        "business_duration_formatted": "4s",
        "communication_and_scheduling_duration_formatted": "1h 32m",
        "social_networking_duration_formatted": "26m 16s",
        "design_and_composition_duration_formatted": "20s",
        "entertainment_duration_formatted": "1h 45m",
        "news_duration_formatted": "12m 52s",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "2m 57s",
        "shopping_duration_formatted": "no time",
        "utilities_duration_formatted": "41m 36s"
    },
    {
        "id": 1499151600,
        "date": "2017-07-04",
        "productivity_pulse": 32,
        "very_productive_percentage": 7.9,
        "productive_percentage": 1.7,
        "neutral_percentage": 44.4,
        "distracting_percentage": 3.1,
        "very_distracting_percentage": 43,
        "all_productive_percentage": 9.6,
        "all_distracting_percentage": 46,
        "uncategorized_percentage": 21.7,
        "business_percentage": 1.6,
        "communication_and_scheduling_percentage": 8.8,
        "social_networking_percentage": 12.9,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 4.8,
        "news_percentage": 16.4,
        "software_development_percentage": 4,
        "reference_and_learning_percentage": 2.3,
        "shopping_percentage": 0.7,
        "utilities_percentage": 26.9,
        "total_hours": 7.71,
        "very_productive_hours": 0.61,
        "productive_hours": 0.13,
        "neutral_hours": 3.42,
        "distracting_hours": 0.24,
        "very_distracting_hours": 3.31,
        "all_productive_hours": 0.74,
        "all_distracting_hours": 3.55,
        "uncategorized_hours": 1.67,
        "business_hours": 0.12,
        "communication_and_scheduling_hours": 0.68,
        "social_networking_hours": 0.99,
        "design_and_composition_hours": 0,
        "entertainment_hours": 0.37,
        "news_hours": 1.26,
        "software_development_hours": 0.31,
        "reference_and_learning_hours": 0.18,
        "shopping_hours": 0.05,
        "utilities_hours": 2.07,
        "total_duration_formatted": "7h 42m",
        "very_productive_duration_formatted": "36m 36s",
        "productive_duration_formatted": "7m 50s",
        "neutral_duration_formatted": "3h 25m",
        "distracting_duration_formatted": "14m 17s",
        "very_distracting_duration_formatted": "3h 18m",
        "all_productive_duration_formatted": "44m 26s",
        "all_distracting_duration_formatted": "3h 33m",
        "uncategorized_duration_formatted": "1h 40m",
        "business_duration_formatted": "7m 19s",
        "communication_and_scheduling_duration_formatted": "40m 51s",
        "social_networking_duration_formatted": "59m 34s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "22m 16s",
        "news_duration_formatted": "1h 15m",
        "software_development_duration_formatted": "18m 28s",
        "reference_and_learning_duration_formatted": "10m 49s",
        "shopping_duration_formatted": "3m 3s",
        "utilities_duration_formatted": "2h 4m"
    },
    {
        "id": 1499065200,
        "date": "2017-07-03",
        "productivity_pulse": 19,
        "very_productive_percentage": 0.1,
        "productive_percentage": 1.9,
        "neutral_percentage": 34.6,
        "distracting_percentage": 3,
        "very_distracting_percentage": 60.4,
        "all_productive_percentage": 2,
        "all_distracting_percentage": 63.4,
        "uncategorized_percentage": 0.1,
        "business_percentage": 0,
        "communication_and_scheduling_percentage": 21.3,
        "social_networking_percentage": 16.5,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 3.1,
        "news_percentage": 20.5,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 0.1,
        "shopping_percentage": 0.1,
        "utilities_percentage": 38.4,
        "total_hours": 4.08,
        "very_productive_hours": 0,
        "productive_hours": 0.08,
        "neutral_hours": 1.41,
        "distracting_hours": 0.12,
        "very_distracting_hours": 2.46,
        "all_productive_hours": 0.08,
        "all_distracting_hours": 2.58,
        "uncategorized_hours": 0,
        "business_hours": 0,
        "communication_and_scheduling_hours": 0.87,
        "social_networking_hours": 0.67,
        "design_and_composition_hours": 0,
        "entertainment_hours": 0.13,
        "news_hours": 0.84,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0,
        "shopping_hours": 0,
        "utilities_hours": 1.57,
        "total_duration_formatted": "4h 4m",
        "very_productive_duration_formatted": "8s",
        "productive_duration_formatted": "4m 41s",
        "neutral_duration_formatted": "1h 24m",
        "distracting_duration_formatted": "7m 24s",
        "very_distracting_duration_formatted": "2h 27m",
        "all_productive_duration_formatted": "4m 49s",
        "all_distracting_duration_formatted": "2h 35m",
        "uncategorized_duration_formatted": "9s",
        "business_duration_formatted": "no time",
        "communication_and_scheduling_duration_formatted": "52m 7s",
        "social_networking_duration_formatted": "40m 18s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "7m 32s",
        "news_duration_formatted": "50m 7s",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "8s",
        "shopping_duration_formatted": "14s",
        "utilities_duration_formatted": "1h 34m"
    },
    {
        "id": 1498978800,
        "date": "2017-07-02",
        "productivity_pulse": 19,
        "very_productive_percentage": 2.9,
        "productive_percentage": 6.6,
        "neutral_percentage": 20.1,
        "distracting_percentage": 5.1,
        "very_distracting_percentage": 65.3,
        "all_productive_percentage": 9.4,
        "all_distracting_percentage": 70.4,
        "uncategorized_percentage": 0.8,
        "business_percentage": 0.5,
        "communication_and_scheduling_percentage": 15.7,
        "social_networking_percentage": 14.1,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 22.2,
        "news_percentage": 14.8,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 2.3,
        "shopping_percentage": 1.6,
        "utilities_percentage": 27.9,
        "total_hours": 4.76,
        "very_productive_hours": 0.14,
        "productive_hours": 0.31,
        "neutral_hours": 0.96,
        "distracting_hours": 0.24,
        "very_distracting_hours": 3.11,
        "all_productive_hours": 0.45,
        "all_distracting_hours": 3.35,
        "uncategorized_hours": 0.04,
        "business_hours": 0.02,
        "communication_and_scheduling_hours": 0.75,
        "social_networking_hours": 0.67,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.06,
        "news_hours": 0.71,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.11,
        "shopping_hours": 0.08,
        "utilities_hours": 1.33,
        "total_duration_formatted": "4h 45m",
        "very_productive_duration_formatted": "8m 10s",
        "productive_duration_formatted": "18m 50s",
        "neutral_duration_formatted": "57m 31s",
        "distracting_duration_formatted": "14m 39s",
        "very_distracting_duration_formatted": "3h 6m",
        "all_productive_duration_formatted": "27m",
        "all_distracting_duration_formatted": "3h 21m",
        "uncategorized_duration_formatted": "2m 25s",
        "business_duration_formatted": "1m 28s",
        "communication_and_scheduling_duration_formatted": "44m 44s",
        "social_networking_duration_formatted": "40m 21s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 3m",
        "news_duration_formatted": "42m 22s",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "6m 42s",
        "shopping_duration_formatted": "4m 39s",
        "utilities_duration_formatted": "1h 19m"
    },
    {
        "id": 1498892400,
        "date": "2017-07-01",
        "productivity_pulse": 26,
        "very_productive_percentage": 14.6,
        "productive_percentage": 7.6,
        "neutral_percentage": 11.4,
        "distracting_percentage": 2.4,
        "very_distracting_percentage": 64,
        "all_productive_percentage": 22.2,
        "all_distracting_percentage": 66.5,
        "uncategorized_percentage": 1.7,
        "business_percentage": 7.6,
        "communication_and_scheduling_percentage": 23.7,
        "social_networking_percentage": 11.9,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 30,
        "news_percentage": 3.8,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 7,
        "shopping_percentage": 0.4,
        "utilities_percentage": 13.8,
        "total_hours": 5.34,
        "very_productive_hours": 0.78,
        "productive_hours": 0.4,
        "neutral_hours": 0.61,
        "distracting_hours": 0.13,
        "very_distracting_hours": 3.42,
        "all_productive_hours": 1.18,
        "all_distracting_hours": 3.55,
        "uncategorized_hours": 0.09,
        "business_hours": 0.4,
        "communication_and_scheduling_hours": 1.27,
        "social_networking_hours": 0.64,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.6,
        "news_hours": 0.21,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.38,
        "shopping_hours": 0.02,
        "utilities_hours": 0.73,
        "total_duration_formatted": "5h 20m",
        "very_productive_duration_formatted": "46m 48s",
        "productive_duration_formatted": "24m 13s",
        "neutral_duration_formatted": "36m 24s",
        "distracting_duration_formatted": "7m 47s",
        "very_distracting_duration_formatted": "3h 25m",
        "all_productive_duration_formatted": "1h 11m",
        "all_distracting_duration_formatted": "3h 32m",
        "uncategorized_duration_formatted": "5m 35s",
        "business_duration_formatted": "24m 16s",
        "communication_and_scheduling_duration_formatted": "1h 16m",
        "social_networking_duration_formatted": "38m 6s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 36m",
        "news_duration_formatted": "12m 19s",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "22m 32s",
        "shopping_duration_formatted": "1m 11s",
        "utilities_duration_formatted": "44m 5s"
    },
    {
        "id": 1498806000,
        "date": "2017-06-30",
        "productivity_pulse": 20,
        "very_productive_percentage": 7.2,
        "productive_percentage": 10.2,
        "neutral_percentage": 9.7,
        "distracting_percentage": 2.3,
        "very_distracting_percentage": 70.6,
        "all_productive_percentage": 17.4,
        "all_distracting_percentage": 72.9,
        "uncategorized_percentage": 5.4,
        "business_percentage": 6.8,
        "communication_and_scheduling_percentage": 25.1,
        "social_networking_percentage": 7.3,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 33.2,
        "news_percentage": 11.3,
        "software_development_percentage": 0.2,
        "reference_and_learning_percentage": 0.7,
        "shopping_percentage": 0,
        "utilities_percentage": 10,
        "total_hours": 10.41,
        "very_productive_hours": 0.75,
        "productive_hours": 1.06,
        "neutral_hours": 1.01,
        "distracting_hours": 0.24,
        "very_distracting_hours": 7.35,
        "all_productive_hours": 1.81,
        "all_distracting_hours": 7.59,
        "uncategorized_hours": 0.56,
        "business_hours": 0.71,
        "communication_and_scheduling_hours": 2.61,
        "social_networking_hours": 0.76,
        "design_and_composition_hours": 0,
        "entertainment_hours": 3.45,
        "news_hours": 1.18,
        "software_development_hours": 0.02,
        "reference_and_learning_hours": 0.07,
        "shopping_hours": 0,
        "utilities_hours": 1.04,
        "total_duration_formatted": "10h 24m",
        "very_productive_duration_formatted": "45m 6s",
        "productive_duration_formatted": "1h 3m",
        "neutral_duration_formatted": "1h",
        "distracting_duration_formatted": "14m 16s",
        "very_distracting_duration_formatted": "7h 21m",
        "all_productive_duration_formatted": "1h 48m",
        "all_distracting_duration_formatted": "7h 35m",
        "uncategorized_duration_formatted": "33m 52s",
        "business_duration_formatted": "42m 26s",
        "communication_and_scheduling_duration_formatted": "2h 36m",
        "social_networking_duration_formatted": "45m 30s",
        "design_and_composition_duration_formatted": "1s",
        "entertainment_duration_formatted": "3h 27m",
        "news_duration_formatted": "1h 10m",
        "software_development_duration_formatted": "1m 16s",
        "reference_and_learning_duration_formatted": "4m 9s",
        "shopping_duration_formatted": "9s",
        "utilities_duration_formatted": "1h 2m"
    },
    {
        "id": 1498719600,
        "date": "2017-06-29",
        "productivity_pulse": 30,
        "very_productive_percentage": 16.1,
        "productive_percentage": 2.6,
        "neutral_percentage": 24.5,
        "distracting_percentage": 1.2,
        "very_distracting_percentage": 55.6,
        "all_productive_percentage": 18.7,
        "all_distracting_percentage": 56.8,
        "uncategorized_percentage": 2,
        "business_percentage": 22.5,
        "communication_and_scheduling_percentage": 32.8,
        "social_networking_percentage": 9.2,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 7.2,
        "news_percentage": 8,
        "software_development_percentage": 0.3,
        "reference_and_learning_percentage": 0.9,
        "shopping_percentage": 0.1,
        "utilities_percentage": 17.2,
        "total_hours": 9.94,
        "very_productive_hours": 1.6,
        "productive_hours": 0.26,
        "neutral_hours": 2.44,
        "distracting_hours": 0.12,
        "very_distracting_hours": 5.53,
        "all_productive_hours": 1.86,
        "all_distracting_hours": 5.65,
        "uncategorized_hours": 0.2,
        "business_hours": 2.23,
        "communication_and_scheduling_hours": 3.26,
        "social_networking_hours": 0.91,
        "design_and_composition_hours": 0,
        "entertainment_hours": 0.71,
        "news_hours": 0.79,
        "software_development_hours": 0.03,
        "reference_and_learning_hours": 0.09,
        "shopping_hours": 0.01,
        "utilities_hours": 1.71,
        "total_duration_formatted": "9h 56m",
        "very_productive_duration_formatted": "1h 35m",
        "productive_duration_formatted": "15m 45s",
        "neutral_duration_formatted": "2h 26m",
        "distracting_duration_formatted": "7m 3s",
        "very_distracting_duration_formatted": "5h 31m",
        "all_productive_duration_formatted": "1h 51m",
        "all_distracting_duration_formatted": "5h 38m",
        "uncategorized_duration_formatted": "11m 59s",
        "business_duration_formatted": "2h 13m",
        "communication_and_scheduling_duration_formatted": "3h 15m",
        "social_networking_duration_formatted": "54m 52s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "42m 45s",
        "news_duration_formatted": "47m 40s",
        "software_development_duration_formatted": "1m 40s",
        "reference_and_learning_duration_formatted": "5m 24s",
        "shopping_duration_formatted": "26s",
        "utilities_duration_formatted": "1h 42m"
    },
    {
        "id": 1498633200,
        "date": "2017-06-28",
        "productivity_pulse": 32,
        "very_productive_percentage": 18,
        "productive_percentage": 11,
        "neutral_percentage": 12.5,
        "distracting_percentage": 1.8,
        "very_distracting_percentage": 56.7,
        "all_productive_percentage": 28.9,
        "all_distracting_percentage": 58.5,
        "uncategorized_percentage": 4,
        "business_percentage": 18.7,
        "communication_and_scheduling_percentage": 40.6,
        "social_networking_percentage": 6,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 6.3,
        "news_percentage": 12.2,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 2.7,
        "shopping_percentage": 1.3,
        "utilities_percentage": 8.2,
        "total_hours": 10.02,
        "very_productive_hours": 1.8,
        "productive_hours": 1.1,
        "neutral_hours": 1.26,
        "distracting_hours": 0.18,
        "very_distracting_hours": 5.68,
        "all_productive_hours": 2.9,
        "all_distracting_hours": 5.86,
        "uncategorized_hours": 0.41,
        "business_hours": 1.88,
        "communication_and_scheduling_hours": 4.06,
        "social_networking_hours": 0.6,
        "design_and_composition_hours": 0,
        "entertainment_hours": 0.63,
        "news_hours": 1.23,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.27,
        "shopping_hours": 0.13,
        "utilities_hours": 0.82,
        "total_duration_formatted": "10h 1m",
        "very_productive_duration_formatted": "1h 47m",
        "productive_duration_formatted": "1h 5m",
        "neutral_duration_formatted": "1h 15m",
        "distracting_duration_formatted": "11m 5s",
        "very_distracting_duration_formatted": "5h 40m",
        "all_productive_duration_formatted": "2h 53m",
        "all_distracting_duration_formatted": "5h 51m",
        "uncategorized_duration_formatted": "24m 20s",
        "business_duration_formatted": "1h 52m",
        "communication_and_scheduling_duration_formatted": "4h 3m",
        "social_networking_duration_formatted": "35m 46s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "37m 47s",
        "news_duration_formatted": "1h 13m",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "16m 9s",
        "shopping_duration_formatted": "7m 51s",
        "utilities_duration_formatted": "49m 12s"
    },
    {
        "id": 1498546800,
        "date": "2017-06-27",
        "productivity_pulse": 19,
        "very_productive_percentage": 7,
        "productive_percentage": 6.1,
        "neutral_percentage": 15.8,
        "distracting_percentage": 2.2,
        "very_distracting_percentage": 68.9,
        "all_productive_percentage": 13.1,
        "all_distracting_percentage": 71.1,
        "uncategorized_percentage": 1.9,
        "business_percentage": 10.4,
        "communication_and_scheduling_percentage": 42.9,
        "social_networking_percentage": 8.9,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 13.8,
        "news_percentage": 9.2,
        "software_development_percentage": 0.1,
        "reference_and_learning_percentage": 1.5,
        "shopping_percentage": 0.4,
        "utilities_percentage": 11,
        "total_hours": 11.82,
        "very_productive_hours": 0.82,
        "productive_hours": 0.72,
        "neutral_hours": 1.87,
        "distracting_hours": 0.26,
        "very_distracting_hours": 8.15,
        "all_productive_hours": 1.55,
        "all_distracting_hours": 8.41,
        "uncategorized_hours": 0.22,
        "business_hours": 1.22,
        "communication_and_scheduling_hours": 5.07,
        "social_networking_hours": 1.06,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.63,
        "news_hours": 1.09,
        "software_development_hours": 0.01,
        "reference_and_learning_hours": 0.17,
        "shopping_hours": 0.05,
        "utilities_hours": 1.3,
        "total_duration_formatted": "11h 49m",
        "very_productive_duration_formatted": "49m 28s",
        "productive_duration_formatted": "43m 16s",
        "neutral_duration_formatted": "1h 52m",
        "distracting_duration_formatted": "15m 27s",
        "very_distracting_duration_formatted": "8h 8m",
        "all_productive_duration_formatted": "1h 32m",
        "all_distracting_duration_formatted": "8h 24m",
        "uncategorized_duration_formatted": "13m 23s",
        "business_duration_formatted": "1h 13m",
        "communication_and_scheduling_duration_formatted": "5h 4m",
        "social_networking_duration_formatted": "1h 3m",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 37m",
        "news_duration_formatted": "1h 5m",
        "software_development_duration_formatted": "30s",
        "reference_and_learning_duration_formatted": "10m 24s",
        "shopping_duration_formatted": "3m 4s",
        "utilities_duration_formatted": "1h 17m"
    },
    {
        "id": 1498460400,
        "date": "2017-06-26",
        "productivity_pulse": 24,
        "very_productive_percentage": 6.5,
        "productive_percentage": 10.4,
        "neutral_percentage": 19,
        "distracting_percentage": 2.4,
        "very_distracting_percentage": 61.7,
        "all_productive_percentage": 16.9,
        "all_distracting_percentage": 64,
        "uncategorized_percentage": 0.6,
        "business_percentage": 10.6,
        "communication_and_scheduling_percentage": 30.6,
        "social_networking_percentage": 8.8,
        "design_and_composition_percentage": 0.1,
        "entertainment_percentage": 6.3,
        "news_percentage": 19.1,
        "software_development_percentage": 0.2,
        "reference_and_learning_percentage": 2.4,
        "shopping_percentage": 5.5,
        "utilities_percentage": 15.8,
        "total_hours": 12.48,
        "very_productive_hours": 0.81,
        "productive_hours": 1.3,
        "neutral_hours": 2.37,
        "distracting_hours": 0.3,
        "very_distracting_hours": 7.69,
        "all_productive_hours": 2.11,
        "all_distracting_hours": 7.99,
        "uncategorized_hours": 0.08,
        "business_hours": 1.33,
        "communication_and_scheduling_hours": 3.82,
        "social_networking_hours": 1.09,
        "design_and_composition_hours": 0.01,
        "entertainment_hours": 0.79,
        "news_hours": 2.38,
        "software_development_hours": 0.02,
        "reference_and_learning_hours": 0.3,
        "shopping_hours": 0.69,
        "utilities_hours": 1.98,
        "total_duration_formatted": "12h 28m",
        "very_productive_duration_formatted": "48m 39s",
        "productive_duration_formatted": "1h 18m",
        "neutral_duration_formatted": "2h 22m",
        "distracting_duration_formatted": "17m 44s",
        "very_distracting_duration_formatted": "7h 41m",
        "all_productive_duration_formatted": "2h 6m",
        "all_distracting_duration_formatted": "7h 59m",
        "uncategorized_duration_formatted": "4m 35s",
        "business_duration_formatted": "1h 19m",
        "communication_and_scheduling_duration_formatted": "3h 48m",
        "social_networking_duration_formatted": "1h 5m",
        "design_and_composition_duration_formatted": "40s",
        "entertainment_duration_formatted": "47m 22s",
        "news_duration_formatted": "2h 22m",
        "software_development_duration_formatted": "1m 21s",
        "reference_and_learning_duration_formatted": "18m 10s",
        "shopping_duration_formatted": "41m 8s",
        "utilities_duration_formatted": "1h 58m"
    },
    {
        "id": 1498374000,
        "date": "2017-06-25",
        "productivity_pulse": 49,
        "very_productive_percentage": 31.6,
        "productive_percentage": 7.8,
        "neutral_percentage": 24.1,
        "distracting_percentage": 1.2,
        "very_distracting_percentage": 35.3,
        "all_productive_percentage": 39.3,
        "all_distracting_percentage": 36.5,
        "uncategorized_percentage": 1.3,
        "business_percentage": 0.6,
        "communication_and_scheduling_percentage": 12.4,
        "social_networking_percentage": 8,
        "design_and_composition_percentage": 0.2,
        "entertainment_percentage": 10.7,
        "news_percentage": 8.9,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 30.7,
        "shopping_percentage": 0.3,
        "utilities_percentage": 26.8,
        "total_hours": 7.14,
        "very_productive_hours": 2.25,
        "productive_hours": 0.55,
        "neutral_hours": 1.72,
        "distracting_hours": 0.09,
        "very_distracting_hours": 2.52,
        "all_productive_hours": 2.81,
        "all_distracting_hours": 2.61,
        "uncategorized_hours": 0.09,
        "business_hours": 0.05,
        "communication_and_scheduling_hours": 0.89,
        "social_networking_hours": 0.57,
        "design_and_composition_hours": 0.01,
        "entertainment_hours": 0.77,
        "news_hours": 0.64,
        "software_development_hours": 0,
        "reference_and_learning_hours": 2.19,
        "shopping_hours": 0.02,
        "utilities_hours": 1.91,
        "total_duration_formatted": "7h 8m",
        "very_productive_duration_formatted": "2h 15m",
        "productive_duration_formatted": "33m 16s",
        "neutral_duration_formatted": "1h 43m",
        "distracting_duration_formatted": "5m 17s",
        "very_distracting_duration_formatted": "2h 31m",
        "all_productive_duration_formatted": "2h 48m",
        "all_distracting_duration_formatted": "2h 36m",
        "uncategorized_duration_formatted": "5m 25s",
        "business_duration_formatted": "2m 45s",
        "communication_and_scheduling_duration_formatted": "53m 9s",
        "social_networking_duration_formatted": "34m 28s",
        "design_and_composition_duration_formatted": "49s",
        "entertainment_duration_formatted": "45m 56s",
        "news_duration_formatted": "38m 7s",
        "software_development_duration_formatted": "9s",
        "reference_and_learning_duration_formatted": "2h 11m",
        "shopping_duration_formatted": "1m 22s",
        "utilities_duration_formatted": "1h 54m"
    },
    {
        "id": 1498287600,
        "date": "2017-06-24",
        "productivity_pulse": 29,
        "very_productive_percentage": 1.8,
        "productive_percentage": 6.2,
        "neutral_percentage": 46.4,
        "distracting_percentage": 1.2,
        "very_distracting_percentage": 44.4,
        "all_productive_percentage": 7.9,
        "all_distracting_percentage": 45.6,
        "uncategorized_percentage": 2.3,
        "business_percentage": 1,
        "communication_and_scheduling_percentage": 11,
        "social_networking_percentage": 10.7,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 17.7,
        "news_percentage": 5.6,
        "software_development_percentage": 0.1,
        "reference_and_learning_percentage": 0.7,
        "shopping_percentage": 1.7,
        "utilities_percentage": 49.4,
        "total_hours": 8.09,
        "very_productive_hours": 0.14,
        "productive_hours": 0.5,
        "neutral_hours": 3.75,
        "distracting_hours": 0.1,
        "very_distracting_hours": 3.59,
        "all_productive_hours": 0.64,
        "all_distracting_hours": 3.69,
        "uncategorized_hours": 0.18,
        "business_hours": 0.08,
        "communication_and_scheduling_hours": 0.89,
        "social_networking_hours": 0.86,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.43,
        "news_hours": 0.45,
        "software_development_hours": 0.01,
        "reference_and_learning_hours": 0.06,
        "shopping_hours": 0.14,
        "utilities_hours": 4,
        "total_duration_formatted": "8h 5m",
        "very_productive_duration_formatted": "8m 36s",
        "productive_duration_formatted": "29m 54s",
        "neutral_duration_formatted": "3h 45m",
        "distracting_duration_formatted": "6m",
        "very_distracting_duration_formatted": "3h 35m",
        "all_productive_duration_formatted": "38m 30s",
        "all_distracting_duration_formatted": "3h 41m",
        "uncategorized_duration_formatted": "11m",
        "business_duration_formatted": "4m 43s",
        "communication_and_scheduling_duration_formatted": "53m 26s",
        "social_networking_duration_formatted": "51m 41s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 25m",
        "news_duration_formatted": "27m 2s",
        "software_development_duration_formatted": "18s",
        "reference_and_learning_duration_formatted": "3m 35s",
        "shopping_duration_formatted": "8m 7s",
        "utilities_duration_formatted": "3h 59m"
    },
    {
        "id": 1498201200,
        "date": "2017-06-23",
        "productivity_pulse": 23,
        "very_productive_percentage": 18.3,
        "productive_percentage": 2.2,
        "neutral_percentage": 6.1,
        "distracting_percentage": 1.2,
        "very_distracting_percentage": 72.3,
        "all_productive_percentage": 20.4,
        "all_distracting_percentage": 73.5,
        "uncategorized_percentage": 1,
        "business_percentage": 18.8,
        "communication_and_scheduling_percentage": 25.1,
        "social_networking_percentage": 4.5,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 15.4,
        "news_percentage": 28,
        "software_development_percentage": 0,
        "reference_and_learning_percentage": 2,
        "shopping_percentage": 1,
        "utilities_percentage": 4.2,
        "total_hours": 9.19,
        "very_productive_hours": 1.68,
        "productive_hours": 0.2,
        "neutral_hours": 0.56,
        "distracting_hours": 0.11,
        "very_distracting_hours": 6.65,
        "all_productive_hours": 1.88,
        "all_distracting_hours": 6.76,
        "uncategorized_hours": 0.09,
        "business_hours": 1.73,
        "communication_and_scheduling_hours": 2.3,
        "social_networking_hours": 0.42,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.41,
        "news_hours": 2.57,
        "software_development_hours": 0,
        "reference_and_learning_hours": 0.19,
        "shopping_hours": 0.09,
        "utilities_hours": 0.38,
        "total_duration_formatted": "9h 11m",
        "very_productive_duration_formatted": "1h 40m",
        "productive_duration_formatted": "11m 55s",
        "neutral_duration_formatted": "33m 31s",
        "distracting_duration_formatted": "6m 39s",
        "very_distracting_duration_formatted": "6h 38m",
        "all_productive_duration_formatted": "1h 52m",
        "all_distracting_duration_formatted": "6h 45m",
        "uncategorized_duration_formatted": "5m 26s",
        "business_duration_formatted": "1h 43m",
        "communication_and_scheduling_duration_formatted": "2h 18m",
        "social_networking_duration_formatted": "25m 1s",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 24m",
        "news_duration_formatted": "2h 34m",
        "software_development_duration_formatted": "no time",
        "reference_and_learning_duration_formatted": "11m 7s",
        "shopping_duration_formatted": "5m 40s",
        "utilities_duration_formatted": "22m 55s"
    },
    {
        "id": 1498114800,
        "date": "2017-06-22",
        "productivity_pulse": 25,
        "very_productive_percentage": 11.6,
        "productive_percentage": 7.3,
        "neutral_percentage": 15.3,
        "distracting_percentage": 1.4,
        "very_distracting_percentage": 64.4,
        "all_productive_percentage": 18.9,
        "all_distracting_percentage": 65.8,
        "uncategorized_percentage": 0.7,
        "business_percentage": 12.1,
        "communication_and_scheduling_percentage": 38.6,
        "social_networking_percentage": 9.1,
        "design_and_composition_percentage": 0,
        "entertainment_percentage": 8.7,
        "news_percentage": 13.8,
        "software_development_percentage": 0.1,
        "reference_and_learning_percentage": 1.8,
        "shopping_percentage": 0.3,
        "utilities_percentage": 14.9,
        "total_hours": 12.21,
        "very_productive_hours": 1.42,
        "productive_hours": 0.9,
        "neutral_hours": 1.87,
        "distracting_hours": 0.17,
        "very_distracting_hours": 7.86,
        "all_productive_hours": 2.31,
        "all_distracting_hours": 8.03,
        "uncategorized_hours": 0.08,
        "business_hours": 1.48,
        "communication_and_scheduling_hours": 4.71,
        "social_networking_hours": 1.11,
        "design_and_composition_hours": 0,
        "entertainment_hours": 1.06,
        "news_hours": 1.68,
        "software_development_hours": 0.01,
        "reference_and_learning_hours": 0.22,
        "shopping_hours": 0.03,
        "utilities_hours": 1.83,
        "total_duration_formatted": "12h 12m",
        "very_productive_duration_formatted": "1h 24m",
        "productive_duration_formatted": "53m 48s",
        "neutral_duration_formatted": "1h 52m",
        "distracting_duration_formatted": "10m 11s",
        "very_distracting_duration_formatted": "7h 51m",
        "all_productive_duration_formatted": "2h 18m",
        "all_distracting_duration_formatted": "8h 1m",
        "uncategorized_duration_formatted": "4m 50s",
        "business_duration_formatted": "1h 28m",
        "communication_and_scheduling_duration_formatted": "4h 42m",
        "social_networking_duration_formatted": "1h 6m",
        "design_and_composition_duration_formatted": "no time",
        "entertainment_duration_formatted": "1h 3m",
        "news_duration_formatted": "1h 40m",
        "software_development_duration_formatted": "53s",
        "reference_and_learning_duration_formatted": "13m 11s",
        "shopping_duration_formatted": "2m 5s",
        "utilities_duration_formatted": "1h 49m"
    }
]

module.exports = dummyData; 